
version: '3.2'

networks:
    jeabc:
        external: 
            name: jeabc
volumes:
    kafka0_data:
    kafka1_data:
    kafka2_data:
    kafka3_data:

services:
        
    k0:
        networks:
            jeabc:
                aliases:
                    - kafka0
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 2s
                max_attempts: 30
            placement:
                constraints:
                    - node.hostname == jeadigital-HP-348-G4
        image: hyperledger/fabric-kafka
        hostname: kafka0
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_BROKER_ID=0
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        volumes:
            - type: volume
              source: kafka0_data
              target: /tmp/kafka-logs
        ports:
         - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2

    k1:
        networks:
            jeabc:
                aliases:
                    - kafka1
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 2s
                max_attempts: 30
            placement:
                constraints:
                    - node.hostname == jeadigital-HP-348-G4
        image: hyperledger/fabric-kafka
        hostname: kafka1
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_BROKER_ID=1
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        volumes:
            - type: volume
              source: kafka1_data
              target: /tmp/kafka-logs
        ports:
         - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2

    k2:
        networks:
            jeabc:
                aliases:
                    - kafka2
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 2s
                max_attempts: 30
            placement:
                constraints:
                    - node.hostname == jeadigital-HP-348-G4
        image: hyperledger/fabric-kafka
        hostname: kafka2
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_BROKER_ID=2
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        volumes:
            - type: volume
              source: kafka2_data
              target: /tmp/kafka-logs
        ports:
         - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2

    k3:
        networks:
            jeabc:
                aliases:
                    - kafka3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 2s
                max_attempts: 30
            placement:
                constraints:
                    - node.hostname == jeadigital-HP-348-G4
        image: hyperledger/fabric-kafka
        hostname: kafka3
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_BROKER_ID=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        volumes:
            - type: volume
              source: kafka3_data
              target: /tmp/kafka-logs
        ports:
         - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
