
version: '3.2'

networks:
    jeabc:
        external: 
            name: jeabc
volumes:
    mysql_data_company:

services:

    mysql_company:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == jeadigital-HP-348-G4
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=fabric_ca
        hostname: mysql.ca.company
        command: mysqld --sql_mode=""
        volumes:
            - type: volume
              source: mysql_data_company
              target: /var/lib/mysql
        ports:
            - 5001:3306
        networks:
            jeabc:
                aliases:
                    - mysql.ca.company

    company:
        networks:
            jeabc:
                aliases:
                    - ca.company.jeabc.com
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == jeadigital-HP-348-G4
        image: hyperledger/fabric-ca:1.1.0
        hostname: ca.company.jeabc.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-company
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.company.jeabc.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d71d9fc239b29863b140bbc7205e3c5303ab0fdb319f0ed4c7f7f4838b92efab_sk
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.company.jeabc.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d71d9fc239b29863b140bbc7205e3c5303ab0fdb319f0ed4c7f7f4838b92efab_sk
            - FABRIC_CA_SERVER_DB_TYPE=mysql
            - FABRIC_CA_SERVER_DB_DATASOURCE=root:root@tcp(mysql.ca.company:3306)/fabric_ca?parseTime=true
        ports:
            - 15312:7054
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.company.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d71d9fc239b29863b140bbc7205e3c5303ab0fdb319f0ed4c7f7f4838b92efab_sk'
        volumes:
            - ../../channel/crypto-config/peerOrganizations/company.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
